image: Visual Studio 2017
environment:
  PREFIX: C:\Deps
  matrix:
    - COMPILER: msvc
    - COMPILER: msys2
platform:
  - x86
  - x64
cache:
  - '%PREFIX% -> .appveyor.yml'
install:
  - |-
    if %COMPILER% NEQ msvc set MSVC=rem
    if %COMPILER% NEQ msys2 set MSYS2=rem
    if exist %PREFIX% set DEP=rem
  - |-
    if %PLATFORM%==x86 (set MSVC_PLATFORM=Win32) else set MSVC_PLATFORM=%PLATFORM%
    if %PLATFORM%==x64 set MSVC_GENERATOR_APPEND= Win64
    if %MSVC_PLATFORM%==x64 set MSVC_SDL_PLATFORM=%MSVC_PLATFORM%
  - |-
    if %PLATFORM%==x86 (set MSYS2_PLATFORM=i686) else set MSYS2_PLATFORM=x86_64
    if %PLATFORM%==x86 (set MSYS2_MSYSTEM=MINGW32) else set MSYS2_MSYSTEM=MINGW64
  - |-
    %DEP% cd %TEMP%
    %DEP% mkdir %PREFIX%\bin
    %DEP% mkdir %PREFIX%\include\SDL2
    %DEP% mkdir %PREFIX%\include\GL
    %DEP% mkdir %PREFIX%\lib
    %MSYS2% set MSYS2_BASH=C:\msys64\usr\bin\bash -lc
  # flex / bison
  - |-
    %MSVC% %DEP% appveyor DownloadFile https://github.com/lexxmark/winflexbison/releases/download/v.2.4.9/win_flex_bison-2.4.9.zip
    %MSVC% %DEP% 7z x win_flex_bison-2.4.9.zip -o%PREFIX%\win_flex_bison > nul
  # glm
  - |-
    %MSVC% %DEP% appveyor DownloadFile https://github.com/g-truc/glm/releases/download/0.9.8.5/glm-0.9.8.5.zip
    %MSVC% %DEP% 7z x glm-0.9.8.5.zip > nul
    %MSVC% %DEP% robocopy glm\glm %PREFIX%\include\glm /S > nul
  # pugixml
  - |-
    %MSVC% %DEP% appveyor DownloadFile http://github.com/zeux/pugixml/releases/download/v1.8/pugixml-1.8.zip
    %MSVC% %DEP% 7z x pugixml-1.8.zip > nul
    %MSVC% %DEP% cmake pugixml-1.8
    %MSVC% %DEP% cmake --build pugixml-1.8 --config Release
    %MSVC% %DEP% copy pugixml-1.8\Release\*.lib %PREFIX%\lib > nul
    %MSVC% %DEP% copy pugixml-1.8\src\*.hpp %PREFIX%\include > nul
  # SDL
  - |-
    %MSVC% %DEP% appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip
    %MSVC% %DEP% 7z x SDL2-devel-2.0.5-VC.zip > nul
    %MSVC% %DEP% copy SDL2-2.0.5\include\* %PREFIX%\include\SDL2 > nul
    %MSVC% %DEP% copy SDL2-2.0.5\lib\%PLATFORM%\*.lib %PREFIX%\lib > nul
    %MSVC% %DEP% copy SDL2-2.0.5\lib\%PLATFORM%\*.dll %PREFIX%\bin > nul
  # SDL_image
  - |-
    %MSVC% %DEP% appveyor DownloadFile https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.1-VC.zip
    %MSVC% %DEP% 7z x SDL2_image-devel-2.0.1-VC.zip > nul
    %MSVC% %DEP% copy SDL2_image-2.0.1\include\* %PREFIX%\include\SDL2 > nul
    %MSVC% %DEP% copy SDL2_image-2.0.1\lib\%PLATFORM%\*.lib %PREFIX%\lib > nul
    %MSVC% %DEP% copy SDL2_image-2.0.1\lib\%PLATFORM%\*.dll %PREFIX%\bin > nul
  # SDL_mixer
  - |-
    %MSVC% %DEP% appveyor DownloadFile https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.1-VC.zip
    %MSVC% %DEP% 7z x SDL2_mixer-devel-2.0.1-VC.zip > nul
    %MSVC% %DEP% copy SDL2_mixer-2.0.1\include\* %PREFIX%\include\SDL2 > nul
    %MSVC% %DEP% copy SDL2_mixer-2.0.1\lib\%PLATFORM%\*.lib %PREFIX%\lib > nul
    %MSVC% %DEP% copy SDL2_mixer-2.0.1\lib\%PLATFORM%\*.dll %PREFIX%\bin > nul
  # GLEW
  - |-
    %MSVC% %DEP% appveyor DownloadFile https://github.com/nigels-com/glew/releases/download/glew-2.0.0/glew-2.0.0-win32.zip
    %MSVC% %DEP% 7z x glew-2.0.0-win32.zip > nul
    %MSVC% %DEP% copy glew-2.0.0\include\GL\* %PREFIX%\include\GL > nul
    %MSVC% %DEP% copy glew-2.0.0\lib\Release\%MSVC_PLATFORM%\*.lib %PREFIX%\lib > nul
    %MSVC% %DEP% copy glew-2.0.0\bin\Release\%MSVC_PLATFORM%\*.dll %PREFIX%\bin > nul
  # MSYS2
  - |-
    %MSYS2% %MSYS2_BASH% "pacman -S --needed --noconfirm mingw-w64-%MSYS2_PLATFORM%-cmake mingw-w64-%MSYS2_PLATFORM%-pugixml mingw-w64-%MSYS2_PLATFORM%-glm mingw-w64-%MSYS2_PLATFORM%-SDL2 mingw-w64-%MSYS2_PLATFORM%-SDL2_image mingw-w64-%MSYS2_PLATFORM%-SDL2_mixer mingw-w64-%MSYS2_PLATFORM%-glew"
before_build:
  - |-
    mkdir %APPVEYOR_BUILD_FOLDER%\build
    cd %APPVEYOR_BUILD_FOLDER%\build
  # Visual Studio
  - |-
    %MSVC% cmake -G"Visual Studio 15 2017%MSVC_GENERATOR_APPEND%" -DCMAKE_PREFIX_PATH=%PREFIX% -DCMAKE_PROGRAM_PATH=%PREFIX%\win_flex_bison ..
  # MSYS2
  - |-
    %MSYS2% %MSYS2_BASH% "MSYSTEM=%MSYS2_MSYSTEM% . /etc/profile && cd '%CD%' && cmake -DCMAKE_PREFIX_PATH='%PREFIX%' -G'MSYS Makefiles' .."
build_script:
  # Visual Studio
  - |-
    %MSVC% cmake --build . --config Release
  # MSYS2
  - |-
    %MSYS2% %MSYS2_BASH% "MSYSTEM=%MSYS2_MSYSTEM% . /etc/profile && cd '%CD%' && make"
